name: Validate TMDL Documentation

on:
  pull_request:
    paths:
      - '**/*.tmdl'

jobs:
  tmdl-doc-check:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run TMDL Documentation Validator
      run: |
        python .github/scripts/validate_tmdl_docs.py --require ${{ env.TMDL_DOC_REQUIRE }}
      env:
        # Set which entities must be documented, comma-separated (e.g. table,column,measure)
        TMDL_DOC_REQUIRE: table,column,measure 
        # ,model,role,partition